// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjXJeYP94d4wqyxOffC48tPzoEj6IKuU',
    appId: '1:1038101042364:web:c34877c5d40f58eedc6cb9',
    messagingSenderId: '1038101042364',
    projectId: 'smart-laptop-monitoring-79348',
    authDomain: 'smart-laptop-monitoring-79348.firebaseapp.com',
    storageBucket: 'smart-laptop-monitoring-79348.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavkI9516R4BlF1nXcAhi3O6dlbweozXU',
    appId: '1:1038101042364:android:d0b86f43857dbe3cdc6cb9',
    messagingSenderId: '1038101042364',
    projectId: 'smart-laptop-monitoring-79348',
    storageBucket: 'smart-laptop-monitoring-79348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg48GXPOgKtkvQZno_JV54AqVgq_F0Juk',
    appId: '1:1038101042364:ios:c6c5a9f80ff7edc9dc6cb9',
    messagingSenderId: '1038101042364',
    projectId: 'smart-laptop-monitoring-79348',
    storageBucket: 'smart-laptop-monitoring-79348.firebasestorage.app',
    iosClientId: '1038101042364-0pllb72mbvl987mvkng6li33ch1ugcf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLaptopMonitoringSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg48GXPOgKtkvQZno_JV54AqVgq_F0Juk',
    appId: '1:1038101042364:ios:c6c5a9f80ff7edc9dc6cb9',
    messagingSenderId: '1038101042364',
    projectId: 'smart-laptop-monitoring-79348',
    storageBucket: 'smart-laptop-monitoring-79348.firebasestorage.app',
    iosClientId: '1038101042364-0pllb72mbvl987mvkng6li33ch1ugcf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLaptopMonitoringSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkjXJeYP94d4wqyxOffC48tPzoEj6IKuU',
    appId: '1:1038101042364:web:ace7233967f70ebadc6cb9',
    messagingSenderId: '1038101042364',
    projectId: 'smart-laptop-monitoring-79348',
    authDomain: 'smart-laptop-monitoring-79348.firebaseapp.com',
    storageBucket: 'smart-laptop-monitoring-79348.firebasestorage.app',
  );
}
